version: "3.9"
services:
  redis:
    image: "redis:7.0.5-alpine3.16@sha256:70633599cb269b224b4b6bfba1e550700b5683dd24f9bd076d75793e05b2b518"
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
  postgres:
    image: "postgres:15.1-alpine3.16@sha256:44b4073d487d0f9baf82bc95d10e2b1f161b18dcc52cfbd0eb2a894b5e2cd513"
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  # shortener-url:
  #   image: "shortener-url"
  #   restart: always
  #   environment:
  #     - REDIS_ADDR=${REDIS_ADDR}
  #     - REDIS_PASS=${REDIS_PASS}
  #     - GRPC_SERVER_PORT=${GRPC_SERVER_PORT}
  #   ports:
  #     #      - "8090:8090"
  #     - "8091:8091"
  #   depends_on:
  #     - redis
  # shortener-api:
  #   image: "shortener-api"
  #   restart: always
  #   environment:
  #     - POSTGRES_ADDR=${POSTGRES_ADDR}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_DB=${POSTGRES_DB}
  #     - GRPC_SERVER_PORT=${GRPC_SERVER_PORT}
  #     - GRPC_SERVER_HOST=${GRPC_SERVER_HOST}
  #     - SHORTENER_API_PORT=${SHORTENER_API_PORT}
  #     - JWT_SECRET_KEY=${JWT_SECRET_KEY}
  #     - JWT_AUTH_TIME_SEC=${JWT_AUTH_TIME_SEC}
  #   ports:
  #     - "8090:8090"
  #   #      - "8091:8091"
  #   depends_on:
  #     - shortener-url
  #     - postgres

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local
