version: "3.9"
services:
  redis:
    image: "redis:7.0.5-alpine3.16@sha256:70633599cb269b224b4b6bfba1e550700b5683dd24f9bd076d75793e05b2b518"
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
  postgres:
    image: "postgres:15.1-alpine3.16@sha256:44b4073d487d0f9baf82bc95d10e2b1f161b18dcc52cfbd0eb2a894b5e2cd513"
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  shortener-redirect:
    image: "shortener-redirect"
    restart: always
    environment:
      - SHORTENER_REDIRECT_STORE_ADDRESS=${SHORTENER_REDIRECT_STORE_ADDRESS}
      - SHORTENER_REDIRECT_STORE_PASSWORD=${SHORTENER_REDIRECT_STORE_PASSWORD}
      - SHORTENER_REDIRECT_API_PORT=${SHORTENER_REDIRECT_API_PORT}
    ports:
      - "8092:8092"
    depends_on:
      - redis
  shortener-url:
    image: "shortener-url"
    restart: always
    environment:
      - SHORTENER_URL_STORE_ADDRESS=${SHORTENER_URL_STORE_ADDRESS}
      - SHORTENER_URL_STORE_PASSWORD=${SHORTENER_URL_STORE_PASSWORD}
      - SHORTENER_URL_GRPC_PORT=${SHORTENER_URL_GRPC_PORT}
    ports:
      - "8091:8091"
    depends_on:
      - redis
  shortener-api:
    image: "shortener-api"
    restart: always
    environment:
      - SHORTENER_API_DB_PASSWORD=${SHORTENER_API_DB_PASSWORD}
      - SHORTENER_API_DB_NAME=${SHORTENER_API_DB_NAME}
      - SHORTENER_API_DB_USER=${SHORTENER_API_DB_USER}
      - SHORTENER_API_DB_HOST=${SHORTENER_API_DB_HOST}
      - SHORTENER_API_DB_PORT=${SHORTENER_API_DB_PORT}
      - SHORTENER_API_AUTH_SECRET_KEY=${SHORTENER_API_AUTH_SECRET_KEY}
      - SHORTENER_API_AUTH_TIME_SEC=${SHORTENER_API_AUTH_TIME_SEC}
      - SHORTENER_API_GRPC_SERVER_PORT=${SHORTENER_API_GRPC_SERVER_PORT}
      - SHORTENER_API_GRPC_SERVER_HOST=${SHORTENER_API_GRPC_SERVER_HOST}
    ports:
      - "8090:8090"
    depends_on:
      - shortener-url
      - postgres

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local
